// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"42tokyo-road-to-dojo-go/pkg/infra/repository"
	"42tokyo-road-to-dojo-go/pkg/presen/handler"
	"42tokyo-road-to-dojo-go/pkg/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitUserHandler(driver *sql.DB) handler.UserHandler {
	userRepository := repository.NewUserRepository(driver)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler
}

func InitCollectionHandler(driver *sql.DB) handler.CollectionHandler {
	userRepository := repository.NewUserRepository(driver)
	userCharaRepository := repository.NewUserCharaRepository(driver)
	collectionUsecase := usecase.NewCollectionUsecase(userRepository, userCharaRepository)
	collectionHandler := handler.NewCollectionHandler(collectionUsecase)
	return collectionHandler
}

func InitRankingHandler(driver *sql.DB) handler.RankingHandler {
	userRepository := repository.NewUserRepository(driver)
	rankingUsecase := usecase.NewRankingUsecase(userRepository)
	rankingHandler := handler.NewRankingHandler(rankingUsecase)
	return rankingHandler
}
