// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"42tokyo-road-to-dojo-go/pkg/infra/repository"
	"42tokyo-road-to-dojo-go/pkg/presen/handler"
	"42tokyo-road-to-dojo-go/pkg/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitUserHandler(driver *sql.DB) handler.UserHandler {
	userRepository := repository.NewUserRepository(driver)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler
}
